# Generated by Django 5.0.4 on 2024-07-06 10:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Expesiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, help_text='bu yerga hechnarsa kiritilmaydi', max_length=90, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='hato_boldi', message='bunda $ @ ^ ', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*])[^?&^]{-}$')])),
                ('img', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
                ('skitka', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gadjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, help_text='bu yerga hechnarsa kiritilmaydi', max_length=90, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='hato_boldi', message='bunda $ @ ^ ', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*])[^?&^]{-}$')])),
                ('img', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
                ('skitka', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, help_text='bu yerga hechnarsa kiritilmaydi', max_length=90, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='hato_boldi', message='bunda $ @ ^ ', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*])[^?&^]{-}$')])),
                ('img', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
                ('skitka', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, help_text='bu yerga hechnarsa kiritilmaydi', max_length=90, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='hato_boldi', message='bunda $ @ ^ ', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*])[^?&^]{-}$')])),
                ('img', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Texnika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, help_text='bu yerga hechnarsa kiritilmaydi', max_length=90, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='hato_boldi', message='bunda $ @ ^ ', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*])[^?&^]{-}$')])),
                ('img', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
                ('skitka', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, help_text='bu yerga hechnarsa kiritilmaydi', max_length=90, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='hato_boldi', message='bunda $ @ ^ kiritib bolmaydi ', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*])[^?&^]{-}$')])),
                ('img', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=250)),
                ('cost', models.CharField(max_length=250, null=True)),
                ('skitka', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, help_text='bu yerga hechnarsa kiritilmaydi', max_length=90, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='hato_boldi', message='bunda $ @ ^ ', regex='^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*])[^?&^]{-}$')])),
                ('img', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
                ('skitka', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expensiv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.expesiv')),
                ('gadjet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.gadjet')),
                ('kitob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.kitob')),
                ('notebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.notebook')),
                ('texnika', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.texnika')),
                ('tovar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.tovar')),
                ('tv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.tv')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.TextField(null=True)),
                ('expensiv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.expesiv')),
                ('gadjet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.gadjet')),
                ('kitob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.kitob')),
                ('notebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.notebook')),
                ('texnika', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.texnika')),
                ('tovar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.tovar')),
                ('tv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.tv')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('expensiv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.expesiv')),
                ('gadjet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.gadjet')),
                ('kitob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.kitob')),
                ('notebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.notebook')),
                ('texnika', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.texnika')),
                ('tovar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.tovar')),
                ('tv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.tv')),
            ],
        ),
    ]
