# Generated by Django 5.0.4 on 2024-07-09 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expesiv',
            new_name='Konditsioner',
        ),
    ]
