# Generated by Django 5.0.6 on 2024-07-10 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_expesiv_konditsioner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, null=True)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('shahar', models.CharField(choices=[('Tanlang', 'Tanlang'), ('Andijon', 'Andijon'), ('Namangan', 'Namangan'), ('Toshkent', 'Toshkent'), ("Farg'ona", "Farg'ona")], default='Tanlang', max_length=20, null=True)),
                ('tuman', models.CharField(choices=[('Tanlang', 'Tanlang'), ('Izboskan', 'Izboskan'), ('Marhamat', 'Marhamat'), ("Oltinko'l", "Oltinko'l"), ('Jalaquduq', 'Jalaquduq')], default='Tanlang', max_length=20, null=True)),
                ('pochta', models.CharField(choices=[('Tanlang', 'Tanlang'), ("Poytug Po'chtasi", "Poytug Po'chtasi")], default='Tanlang', max_length=20, null=True)),
                ('address', models.CharField(max_length=100)),
                ('orienter', models.CharField(max_length=100)),
                ('working_adress', models.CharField(max_length=100)),
                ('date_orderded', models.DateTimeField(auto_now_add=True)),
                ('expensiv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.konditsioner')),
                ('gadjet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.gadjet')),
                ('kitob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.kitob')),
                ('notebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.notebook')),
                ('texnika', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.texnika')),
                ('tovar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.tovar')),
                ('tv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.tv')),
            ],
        ),
    ]
