# Generated by Django 5.0.6 on 2024-07-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_reyting'),
    ]

    operations = [
        migrations.AddField(
            model_name='reyting',
            name='baholash',
            field=models.CharField(default=['1', '1', '2', '2', '3', '3'], max_length=10),
        ),
    ]
